const jsonSearchTest = {
    website: "test",
    originID: "637e6ddd6f08548095f37405",
    websiteAlts: 103,
    registeredAlts: [
      { domain: "test-shop", id: "637e6ddd6f08548095f37304" },
      { domain: "test-net", id: "637e6ddc6f08548095f372c7" },
      { domain: "tests", id: "637e6ddd6f08548095f37e7d" },
      { domain: "te-st", id: "637e6dd26f08548095f256f0" },
      { domain: "teste", id: "637e6ddd6f08548095f377a9" },
    ],
    registeredAltsNumber: 5,
    unRegisteredAlts: [
      "test-com",
      "test-ca",
      "test-gov",
      "test-store",
      "teest",
      "test-org",
      "tes-t",
      "test-ccom",
      "test-coom",
      "test-oorg",
      "test-cca",
      "test-goov",
      "test-shoop",
      "test-stoore",
      "t-est-com",
      "te-st-com",
      "test-c-om",
      "test-co-m",
      "te-st-org",
      "test-o-rg",
      "test-or-g",
      "t-est",
      "te-st-net",
      "test-n-et",
      "test-ne-t",
      "t-est-ca",
      "te-st-ca",
      "test-c-a",
      "t-est-gov",
      "test-go-v",
      "te-st-gov",
      "t-est-shop",
      "test-g-ov",
      "te-st-shop",
      "test-s-hop",
      "test-sh-op",
      "test-sho-p",
      "t-est-store",
      "te-st-store",
      "test-s-tore",
      "test-st-ore",
      "test-sto-re",
      "test-stor-e",
      "t-est-org",
      "te-est",
      "tee-st",
      "tees-t",
      "t-este",
      "te-ste",
      "test-e",
      "tes-te",
      "t-ests",
      "te-sts",
      "tes-ts",
      "t-est-net",
      "t-e-st",
      "t-es-t",
      "t-es-t",
      "t-est-coom",
      "te-s-t",
      "test-c-oom",
      "te-st-coom",
      "test-co-om",
      "te-st-ccom",
      "test-c-com",
      "test-coo-m",
      "test-cc-om",
      "test-cco-m",
      "t-est-ccom",
      "t-est-oorg",
      "test-o-org",
      "test-oo-rg",
      "te-st-oorg",
      "test-oor-g",
      "te-st-cca",
      "t-est-cca",
      "test-c-ca",
      "test-cc-a",
      "t-est-goov",
      "te-st-goov",
      "test-g-oov",
      "test-go-ov",
      "test-goo-v",
      "t-est-shoop",
      "te-st-shoop",
      "test-s-hoop",
      "test-sh-oop",
      "test-sho-op",
      "t-eest",
      "t-est-stoore",
      "te-st-stoore",
      "test-s-toore",
      "test-sto-ore",
      "test-st-oore",
      "test-stoo-re",
      "test-stoor-e",
      "test-s",
      "test-shoo-p",
    ],
    unRegisteredAltsNumber: 98,
    whoDis: [
      {
        domainName: 'TESTS.ORG',
        registrar: 'GoDaddy.com, LLC',
        registrarWhoisServer: 'whois.godaddy.com',
        registrarUrl: 'https://www.godaddy.com',
        updatedDate: '2022-11-24T13:01:43Z',
        creationDate: '1999-11-23T21:40:23Z',
        registrarAbuseContactEmail: 'abuse@godaddy.com',
        registrarAbuseContactPhone: '+1.4806242505',
        registrantCountry: 'US',
        registrantStateProvince: 'Arizona'
      },
      {
        domainName: 'test-net.org',
        registrar: 'Wild West Domains, LLC',
        registrarWhoisServer: 'whois.wildwestdomains.com',
        registrarUrl: 'https://www.wildwestdomains.com',
        updatedDate: '2022-12-31T06:02:15Z',
        creationDate: '2014-11-03T20:23:48Z',
        registrarAbuseContactEmail: 'abuse@wildwestdomains.com',
        registrarAbuseContactPhone: '+1.4806242505',
        registrantCountry: 'US',
        registrantStateProvince: 'Arizona'
      },
      {
        domainName: 'teste.org',
        registrar: 'Key-Systems GmbH',
        registrarWhoisServer: 'whois.rrpproxy.net',
        registrarUrl: 'http://www.key-systems.net',
        updatedDate: '2023-02-13T14:30:30Z',
        creationDate: '2014-02-13T14:30:14Z',
        registrarAbuseContactEmail: 'abusereport@key-systems.net',
        registrarAbuseContactPhone: '+49.68949396850',
        registrantCountry: 'DE',
        registrantStateProvince: 'Registrant Postal Code: REDACTED FOR PRIVACY'
      },
      {
        domainName: 'te-st',
        error: '{"errno":-4078,"code":"ECONNREFUSED","syscall":"connect","address":"74.220.199.10","port":43}'
      },
      {
        domainName: 'test-shop',
        error: '{"errno":-4039,"code":"ETIMEDOUT","syscall":"connect","address":"192.166.192.122","port":43}'
      }
    ]
  };

  export const testData = jsonSearchTest;